name: Update README for Java Project
on:
  push:
    branches:
      - main # ou a branch que você deseja monitorar
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Update README
        run: |
           # Descrição do projeto - Read-me em teste!
           echo "Documentação atualizada em $(date)" >> README.md
           PR_TITLE=$(git log -1 --pretty=%B)
           echo "## Changelog" >> README.md
           echo "- ${PR_TITLE}" >> README.md          
           # Adiciona a versão atual do projeto
           PROJECT_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
           echo "## Versão Atual" >> README.md
           echo "- ${PROJECT_VERSION}" >> README.md          
           # Lista de autores das mudanças
           echo "## Autores das Mudanças" >> README.md
           git log --format="%an" | sort | uniq | while read author; do echo "- ${author}"; done >> README.md          
           # Link para a documentação gerada - em teste
           echo "## Documentação" >> README.md
           echo "- [Javadoc](path/to/javadoc/index.html)" >> README.md

      - name: Archive README
        uses: actions/upload-artifact@v2
        with:
          name: Updated-README
          path: README.md